apiVersion: v1
kind: Pod
metadata:
  name: acm-test-pod
  namespace : feature-busybox
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: acm-test-container